name: CD
on:
  push:
    tags:
      - '*'
    
jobs:
  publish-image-github-packages:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Login with Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image          
        run: |
            docker build . --tag ghcr.io/basim108/hrim-analytics-api:${{github.ref_name}}
            docker image tag ghcr.io/basim108/hrim-analytics-api:${{github.ref_name}} ghcr.io/basim108/hrim-analytics-api:latest

      - name: Publish Docker image
        run: |
          docker push ghcr.io/basim108/hrim-analytics-api:latest
          docker push ghcr.io/basim108/hrim-analytics-api:${{github.ref_name}}

  publish-image-docker-hub:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Log in to Docker Hub
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: basimdev/hrim-event-analytics-api

        - name: Build and push Docker image
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
