name: CD
on:
  push:
    branches: [main]
    
jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - uses: actions/checkout@v2

      - name: Login with Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish Docker image          
        run: |
            docker build . --tag ghcr.io/basim108/hrim-analytics-api:latest
            docker push ghcr.io/basim108/hrim-analytics-api:latest
            docker push ghcr.io/basim108/hrim-analytics-api:${{github.ref_name}}
