name: CD
on:
  push:
    tags:
      - '*'
    
jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Login with Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image          
        run: |
            docker build . --tag ghcr.io/basim108/hrim-analytics-api:${{github.ref_name}}
            docker image tag ghcr.io/basim108/hrim-analytics-api:${{github.ref_name}} ghcr.io/basim108/hrim-analytics-api:latest

      - name: Publish Docker image
        run: |
          docker push ghcr.io/basim108/hrim-analytics-api:latest
          docker push ghcr.io/basim108/hrim-analytics-api:${{github.ref_name}}
