name: CD
on:
  push:
    branches:
      - 'main'
jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - uses: actions/checkout@v2
      - name: Build and Publish Docker image
        uses: VaultVulp/gp-docker-action@1.1.12
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: hrim-analytics-api
          extract-git-tag: true 